name: build and push

on:
  push:
    branches: ['main', 'master']
  workflow_dispatch:
  schedule:
    # Runs every day At 08:00.
    - cron: '0 8 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/podman:latest"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
